---
- name: gtb agent install
  hosts: all
  tasks:
   - name: download the agent
     win_get_url:
       url: "{{ AGENT }}"
       dest: C:\gtb\agent\GTBEndpointAgent.msi
  
   - name: Install the Agent
     win_package:
       path: C:\gtb\agent\GTBEndpointAgent.msi
       state: present

